# IMPORTING NECESSARY MODULE

In [1]:
import pandas as pd;
import numpy as np;

# CONVERTING TO CSV FILE

In [2]:
# data = pd.read_csv("breast-cancer-wisconsin.data")
# data.columns = ["id number","Clump Thickness","Uniformity of Cell Size","Uniformity of Cell Shape","Marginal Adhesion",
#                "Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli","Mitoses",
#                 "Class:(2 for benign, 4 for malignant)"]
# data.to_csv("Breast_Cancer_Detection_Data.csv",index = None,header = True)

# DATA PREPROCESSING

In [3]:
dataset = pd.read_csv("Data/Breast_Cancer_Detection_Data.csv", na_values=["?"])
# Explicitly declaring "?" as null value.
# By default Pandas treat "?" as a regular value.
missing_values = dataset.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
id number                                 0
Clump Thickness                           0
Uniformity of Cell Size                   0
Uniformity of Cell Shape                  0
Marginal Adhesion                         0
Single Epithelial Cell Size               0
Bare Nuclei                              16
Bland Chromatin                           0
Normal Nucleoli                           0
Mitoses                                   0
Class:(2 for benign, 4 for malignant)     0
dtype: int64


In [4]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id number                              698 non-null    int64  
 1   Clump Thickness                        698 non-null    int64  
 2   Uniformity of Cell Size                698 non-null    int64  
 3   Uniformity of Cell Shape               698 non-null    int64  
 4   Marginal Adhesion                      698 non-null    int64  
 5   Single Epithelial Cell Size            698 non-null    int64  
 6   Bare Nuclei                            682 non-null    float64
 7   Bland Chromatin                        698 non-null    int64  
 8   Normal Nucleoli                        698 non-null    int64  
 9   Mitoses                                698 non-null    int64  
 10  Class:(2 for benign, 4 for malignant)  698 non-null    int64  
dtypes: flo

In [5]:
dataset.replace('?',np.nan,inplace=True) # Replacing '?' by 'nan' values.
dataset.dropna(inplace=True)             # Droping the missing_values.

In [6]:
dataset.isnull().sum()                   # Checking that is there any missing value left or not.

id number                                0
Clump Thickness                          0
Uniformity of Cell Size                  0
Uniformity of Cell Shape                 0
Marginal Adhesion                        0
Single Epithelial Cell Size              0
Bare Nuclei                              0
Bland Chromatin                          0
Normal Nucleoli                          0
Mitoses                                  0
Class:(2 for benign, 4 for malignant)    0
dtype: int64

In [7]:
x = dataset.iloc[:,1:-1].values #Note : As id number will not help in determing the type of tumor,so we are dropping it.
y = dataset.iloc[:,-1].values

In [8]:
print(x)

[[ 5.  4.  4. ...  3.  2.  1.]
 [ 3.  1.  1. ...  3.  1.  1.]
 [ 6.  8.  8. ...  3.  7.  1.]
 ...
 [ 5. 10. 10. ...  8. 10.  2.]
 [ 4.  8.  6. ... 10.  6.  1.]
 [ 4.  8.  8. ... 10.  4.  1.]]


In [9]:
print(y)

[2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2 4
 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2 2
 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4 4
 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4 4
 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4 4
 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4 2
 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4 4
 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2 4
 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 4 2 2 2
 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2
 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4 2
 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2 2
 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2 2
 2 2 2 2 2 2 2 2 2 4 2 2 

# SPLITTING INTO TRAIN SET AND TEST SET

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [11]:
print(x_train)

[[1. 1. 1. ... 2. 1. 1.]
 [5. 1. 1. ... 3. 1. 1.]
 [3. 3. 5. ... 7. 1. 1.]
 ...
 [3. 1. 1. ... 2. 1. 1.]
 [1. 2. 2. ... 1. 1. 1.]
 [5. 1. 2. ... 3. 1. 1.]]


In [12]:
print(y_train)

[2 2 4 2 4 4 4 2 4 4 2 4 2 4 4 4 4 2 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2 2
 4 2 2 2 2 2 4 2 2 4 2 2 4 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 4 2 4 4 2 4 2 4
 2 2 4 4 2 4 4 2 2 4 2 4 2 2 2 2 4 4 4 2 2 2 4 2 4 4 2 4 2 2 2 4 4 4 2 4 2
 2 4 4 2 2 4 4 2 2 2 2 4 2 4 4 2 2 2 4 2 2 4 4 2 2 4 4 2 2 4 2 2 2 2 2 2 2
 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4 4 4 4 2 4 2 2 2 2
 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 2 2 2 2 2 4 2 4 2 2 2 2 4 2 4 2 2 4 4 4 2 4
 4 4 2 4 2 4 2 4 2 4 2 4 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 4 4 2 4 2 4 2 4 2 4
 2 4 2 4 2 2 2 2 2 2 2 4 2 2 2 2 4 2 4 4 2 4 2 2 2 4 2 2 2 4 2 2 4 4 4 2 2
 4 2 4 2 2 2 2 2 2 2 2 4 4 4 2 2 4 4 4 2 4 2 4 2 2 4 2 4 2 2 4 2 2 2 2 2 4
 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 2 2 2 4 2 2 2 4 2 2 2 2 2 4 2
 2 2 4 4 4 4 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 4 4 2 4 2 2 2 4 2 2 4 4 4 2 2
 2 2 4 2 2 2 2 2 2 2 4 2 4 2 4 2 2 4 4 2 2 2 4 2 2 4 4 2 2 4 2 2 2 2 2 4 4
 2 4 2 4 4 2 2 2 4 4 4 2 2 4 2 4 2 2 2 2 2 4 2 4 2 2 4 2 2 2 2 2 2 2 2 4 2
 4 4 4 4 4 2 4 2 4 2 4 4 

# TRAINING THE LOGISTIC REGRESSION MODEL IN TRAINING SET

In [13]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

# PREDICTING THE VALUES OF TEST_SET

In [14]:
y_pred = classifier.predict(x_test)

In [15]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]]


# MAKING THE CONFUSION MATRIX

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[89  3]
 [ 2 43]]


In [17]:
ac = accuracy_score(y_test,y_pred)
ac = round(ac, 2)
print("Accuracy : " , ac)

Accuracy :  0.96


# COMPUTING THE ACCURACY OF K_FOLD CROSS VALIDATION

In [18]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
print("Accuracies : {:.2f} %".format(accuracies.mean()*100))
print("Accuracies : {:.2f} %".format(accuracies.std()*100))

Accuracies : 96.70 %
Accuracies : 2.28 %
